/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inversa_matriz;

import javax.swing.JOptionPane;

/**
 *
 * @author vladi
 */
public class Invesrsa_de_una_Matriz extends javax.swing.JFrame {
    double trans1,trans2,trans3,trans4,trans5,trans6,trans7,trans8,trans9;
    double adjT1,adjT2,adjT3,adjT4,adjT5,adjT6,adjT7,adjT8,adjT9;
    double div;
    double mDiv1,mDiv2,mDiv3,mDiv4,mDiv5,mDiv6,mDiv7,mDiv8,mDiv9;
    double cs2,cs4,cs6,cs8;//variables que guardan "n" numero y le cambia de signo 
                          //(si es positivo lo cambia a negativo o viceversa)
    
    /**
     * Creates new form Invesrsa_de_una_Matriz
     */
    public Invesrsa_de_una_Matriz() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        lbR1.setText("");
        lbR2.setText("");
        lbR3.setText("");
        lbR4.setText("");
        lbR5.setText("");
        lbR6.setText("");
        lbR7.setText("");
        lbR8.setText("");
        lbR9.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCamp2 = new javax.swing.JTextField();
        txtCamp3 = new javax.swing.JTextField();
        txtCamp4 = new javax.swing.JTextField();
        txtCamp1 = new javax.swing.JTextField();
        txtCamp5 = new javax.swing.JTextField();
        txtCamp6 = new javax.swing.JTextField();
        txtCamp7 = new javax.swing.JTextField();
        txtCamp8 = new javax.swing.JTextField();
        txtCamp9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbR2 = new javax.swing.JLabel();
        lbR3 = new javax.swing.JLabel();
        lbR4 = new javax.swing.JLabel();
        lbR1 = new javax.swing.JLabel();
        lbR5 = new javax.swing.JLabel();
        lbR6 = new javax.swing.JLabel();
        lbR8 = new javax.swing.JLabel();
        lbR9 = new javax.swing.JLabel();
        lbR7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        txtCamp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp2ActionPerformed(evt);
            }
        });

        txtCamp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp3ActionPerformed(evt);
            }
        });

        txtCamp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp4ActionPerformed(evt);
            }
        });

        txtCamp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp1ActionPerformed(evt);
            }
        });

        txtCamp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp5ActionPerformed(evt);
            }
        });

        txtCamp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp6ActionPerformed(evt);
            }
        });

        txtCamp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp7ActionPerformed(evt);
            }
        });

        txtCamp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp8ActionPerformed(evt);
            }
        });

        txtCamp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamp9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCamp7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtCamp4)
                    .addComponent(txtCamp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCamp2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCamp5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtCamp8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCamp6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCamp3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCamp5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCamp7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCamp9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lbR2.setText("Resultado");

        lbR3.setText("Resultado");

        lbR4.setText("Resultado");

        lbR1.setText("Resultado");

        lbR5.setText("Resultado");

        lbR6.setText("Resultado");

        lbR8.setText("Resultado");

        lbR9.setText("Resultado");

        lbR7.setText("Resultado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbR4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbR8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbR5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbR2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbR3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbR2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbR4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbR8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbR7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Ingrese los datos de la matriz:");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setText("Resultado de la matriz inversa: ");

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("Buscar Inversa.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Determinate:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("CALCULAR LA INVERSA DE UNA MATRIZ USANDO EL MÉTODO DE LA DETERMINANTE+TRANSPUESTA+ADJUNTA");

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCamp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp2ActionPerformed

    private void txtCamp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp3ActionPerformed

    private void txtCamp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp4ActionPerformed

    private void txtCamp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp1ActionPerformed

    private void txtCamp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp5ActionPerformed

    private void txtCamp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp6ActionPerformed

    private void txtCamp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp7ActionPerformed

    private void txtCamp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp8ActionPerformed

    private void txtCamp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamp9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamp9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            double posic1=Double.parseDouble(txtCamp1.getText());
            double posic2=Double.parseDouble(txtCamp2.getText());
            double posic3=Double.parseDouble(txtCamp3.getText());
            double posic4=Double.parseDouble(txtCamp4.getText());
            double posic5=Double.parseDouble(txtCamp5.getText());
            double posic6=Double.parseDouble(txtCamp6.getText());
            double posic7=Double.parseDouble(txtCamp7.getText());
            double posic8=Double.parseDouble(txtCamp8.getText());
            double posic9=Double.parseDouble(txtCamp9.getText());
            
            //Determinate por el metodo de Sarrus
            double p1 = posic1*posic5*posic9;
            double p2 = posic4*posic8*posic3;
            double p3 = posic7*posic2*posic6;
            
            double resultado1 = p1+p2+p3;
            
            double n1 = posic3*posic5*posic7;
            double n2 = posic6*posic8*posic1;
            double n3 = posic9*posic2*posic4;
            
            double resultado2 = n1+n2+n3;
            double determinante = resultado1-resultado2;
            jTextField1.setText(""+determinante);
            
            //Transpuesta = convertimos filas a columnas
            trans1=posic1;
            trans2=posic4;
            trans3=posic7;
            trans4=posic2;
            trans5=posic5;
            trans6=posic8;
            trans7=posic3;
            trans8=posic6;
            trans9=posic9;
            
            //Adjunta
            adjT1=(trans5*trans9)-(trans6*trans8);
            adjT2=(trans4*trans9)-(trans6*trans7);
            adjT3=(trans4*trans8)-(trans5*trans7);
            adjT4=(trans2*trans9)-(trans3*trans8);
            adjT5=(trans1*trans9)-(trans3*trans7);
            adjT6=(trans1*trans8)-(trans2*trans7);
            adjT7=(trans2*trans6)-(trans3*trans5);
            adjT8=(trans1*trans6)-(trans3*trans4);
            adjT9=(trans1*trans5)-(trans2*trans4);
            
            //inversa
            
            div=1/determinante;
            
            mDiv1=div*adjT1;
            mDiv2=div*adjT2;
            mDiv3=div*adjT3;
            mDiv4=div*adjT4;
            mDiv5=div*adjT5;
            mDiv6=div*adjT6;
            mDiv7=div*adjT7;
            mDiv8=div*adjT8;
            mDiv9=div*adjT9;
            //multiplicacion para el cambio de signo
            cs2=mDiv2*-1;
            cs4=mDiv4*-1;
            cs6=mDiv6*-1;
            cs8=mDiv8*-1;
            
            lbR1.setText(""+mDiv1);
            lbR2.setText(""+cs2);//cambia de signo
            lbR3.setText(""+mDiv3);
            lbR4.setText(""+cs4);//cambia de signo
            lbR5.setText(""+mDiv5);
            lbR6.setText(""+cs6);//cambia de signo
            lbR7.setText(""+mDiv7);
            lbR8.setText(""+cs8);//cambia de signo
            lbR9.setText(""+mDiv9);
            
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al encontrar inversa");
            lbR1.setText("");
            lbR2.setText("");
            lbR3.setText("");
            lbR4.setText("");
            lbR5.setText("");
            lbR6.setText("");
            lbR7.setText("");
            lbR8.setText("");
            lbR9.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(this,"¿Seguro que desea salir?")>0) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invesrsa_de_una_Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invesrsa_de_una_Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invesrsa_de_una_Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invesrsa_de_una_Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invesrsa_de_una_Matriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbR1;
    private javax.swing.JLabel lbR2;
    private javax.swing.JLabel lbR3;
    private javax.swing.JLabel lbR4;
    private javax.swing.JLabel lbR5;
    private javax.swing.JLabel lbR6;
    private javax.swing.JLabel lbR7;
    private javax.swing.JLabel lbR8;
    private javax.swing.JLabel lbR9;
    private javax.swing.JTextField txtCamp1;
    private javax.swing.JTextField txtCamp2;
    private javax.swing.JTextField txtCamp3;
    private javax.swing.JTextField txtCamp4;
    private javax.swing.JTextField txtCamp5;
    private javax.swing.JTextField txtCamp6;
    private javax.swing.JTextField txtCamp7;
    private javax.swing.JTextField txtCamp8;
    private javax.swing.JTextField txtCamp9;
    // End of variables declaration//GEN-END:variables
}
